Refactor

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,9 +1,51 @@
-#!/bin/bash
-set -eu
-
 readonly SRC_DIR="$(cd $(dirname "$0") && pwd)"
-source "${SRC_DIR}/slack.sh"
+source "${SRC_DIR}/variables.conf"
 
+##################################################
+# Raspberry Pi functions
+##################################################
+function rpi::camera() {
+  local tmp_file="$(mktemp)"
+  raspistill -vf -hf -o "${tmp_file}" -w 640 -h 480 1>&2  # for logging
+  echo "${tmp_file}"  # for return value
+}
+
+##################################################
+# Slack functions
+##################################################
+readonly SLACK_FILE_UPLOAD_URL="https://slack.com/api/files.upload"
+
+function slack::upload_file() {
+  local file="$1"
+  local unix_time="$(date '+%s')"
+  local response="$(curl -fsL \
+                         -F "token=${SLACK_OAUTH_TOKEN}" \
+                         -F "channels=${SLACK_CHANNEL_ID}" \
+                         -F "file=@${file}" \
+                         -F "filename=${unix_time}.jpg" \
+                         "${SLACK_FILE_UPLOAD_URL}")"
+  echo "${response}" | python -c 'import sys; import json; sys.exit(0 if json.loads(raw_input())["ok"] else 1)'
+}
+
+function slack::create_payload() {
+  local text="$1"
+  cat <<EOF
+{
+  "text": "${text}",
+  "blocks": []
+}
+EOF
+}
+
+function slack::post() {
+  local text="$1"
+  local payload="$(slack::create_payload "${text}")"
+  curl -fsL -X POST --data "${payload}" "${SLACK_WEBHOOK_URL}" >/dev/null
+}
+
+##################################################
+# Witty Pi 3 functions
+##################################################
 function witty::schedule() {
   if [ -f "${SRC_DIR}/schedule.wpi.md5" ]; then
     set +e
@@ -59,10 +101,3 @@ function witty::parameter() {
   send \"11\n\"
   "
 }
-
-function main() {
-  witty::schedule
-  witty::parameter 2 100 255
-}
-
-main "$@"
